"""Phase 7: draft consultation summary storage + clinician-approval gate.
The summary itself is generated by clinical-nlp's LLM-backed summarizer
(app/summarization -- AGENT_INSTRUCTIONS.md Section 2: orchestrator doesn't
run inference itself, it calls the service whose job that is). This module
owns the draft/approved lifecycle for that summary within a session."""
